# NumPy


In [1]:
import numpy as np

## Array Dimensions

In [2]:
arr_0d = np.array(10)
print(arr_0d)
print("Dimensions:", arr_0d.ndim)

arr_1d = np.array([1, 2, 3, 4])
print(arr_1d)
print("Dimensions:", arr_1d.ndim)

arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(arr_2d)
print("Dimensions:", arr_2d.ndim)

arr_3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
])
print(arr_3d)
print("Dimensions:", arr_3d.ndim)

more_dimensions = np.array([1, 2, 3], ndmin=10)
print(more_dimensions)
     



10
Dimensions: 0
[1 2 3 4]
Dimensions: 1
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensions: 2
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Dimensions: 3
[[[[[[[[[[1 2 3]]]]]]]]]]


## Building arrays

In [14]:
#Full(shape, value)
arr_full = np.full((3, 2, 1), 'x')
print(arr_full)

# The argument (3, 2, 1) gives us three sets with two rows and one column each

arr_zeros = np.zeros((3, 3, 3))
print("\nZeros", arr_zeros)

# ones(shape)
arr_ones = np.ones((3, 3, 3))
print("\nOnes", arr_ones)

# arrange(start, stop, step)
arr_arange = np.arange(10, 100, 10)
print("\nArange", arr_arange)

# linspace(start, stop, num)
arr_linspace = np.linspace(20, 50, 6)
print("\nLinspace", arr_linspace)

# empty(shape) + fill(value)
arr_empty = np.empty((5, 5))
arr_empty.fill(1)
print("\nFilled", arr_empty)



[[['x']
  ['x']]

 [['x']
  ['x']]

 [['x']
  ['x']]]

Zeros [[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]

Ones [[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]

Arange [10 20 30 40 50 60 70 80 90]

Linspace [20. 26. 32. 38. 44. 50.]

Filled [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## Looking at the Shape of an Array

NumPy arrays have a shape, which describes the number of dimensions and the size of each dimension.

(2, 3, 3) → 2 layers, each with 3 rows and 3 columns

In other words:
- There are 2 two-dimensional arrays
- Each 2D array contains 3 one-dimensional arrays (rows)
- Each 1D array contains 3 zero-dimensional values (scalars)

In [ ]:
# Reshaping changes the shape of an array WITHOUT changing its data.
# The total number of elements must stay the same

## Your Turn

Create a NumPy array containing 10 elements. Practice reshaping it into as many different valid shapes as possible.


## Array indexing 

In [ ]:
arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])


## Slicing

In [18]:
arr = np.array([1,2,3,4,5,6])
print(arr[:3])

print(arr[3:])

print(arr[::2]) # colons show every element, 2 shows step size

print(arr[1::2])

print(arr[-4:-2])



[1 2 3]
[4 5 6]
[1 3 5]
[2 4 6]
[3 4]


In [19]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(arr[1, :2])
print(arr[:2, 1:])

[4 5]
[[2 3]
 [5 6]]


## Your turn: 
Slice this from the array below this
 [[ 1,  3],
  [ 7,  9]]

# Looping through arrays
NumPy has tools that reduce the need for loops, but let’s take a look at how this works in vanilla Python.

Lets make it easier

In [20]:
# nditer
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

for i in np.nditer(arr):
    print(i)


1
2
3
4
5
6
7
8
9
1
2
3
4
5
6
7
8
9


## Joining Arrays


In [21]:
# SQL joins are based off keys
# NumPy joins are based off axes

nums1 = np.array([1,2,3])
nums2 = np.array([1,2,3])

all_nums = np.concatenate((nums1, nums2))
print(all_nums)

[1 2 3 1 2 3]


In [24]:
nums1_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
])

nums2_2d = np.array([
    [5, 6, 7],
    [8, 9, 10],
])

# Stacks
# Add a new axis
stack = np.stack((nums1_2d, nums2_2d))
print(stack)

print()

# hstack joins arrays side by side by side
hstack = np.hstack((nums1_2d, nums2_2d))
print(hstack)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 5  6  7]
  [ 8  9 10]]]

[[ 1  2  3  5  6  7]
 [ 4  5  6  8  9 10]]


## Splitting arrays

## Where 
Who needs loops when you have where

## Your Turn

Given the array below, use np.where() to find the indices of all values that are between 0.3 and 0.7 (inclusive).
arr = np.array([0.15, 0.32, 0.58, 0.71, 0.44, 0.89, 0.67])
Hint you can use the '&' operator 


## Comparing 

## Boolean Indexing
Boolean indexing can simplify data for ML models.

## Conditions 


In [25]:
scores = np.array([0.85, 0.42, 0.90, 0.67, 0.30])
cond = scores > 0.5
print(cond)

[ True False  True  True False]


## Math
- mean
- sum - total
- cumsum - sum as we go